# Generated by Django 4.2.2 on 2023-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rating', models.FloatField(default=0)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('video', models.FileField(upload_to='videos/')),
                ('fragman', models.FileField(upload_to='fragmans/')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
    ]
