# Generated by Django 4.2.2 on 2023-06-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_actormodel_filmmodel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='film.actormodel'),
        ),
    ]
