# Generated by Django 4.2.3 on 2023-07-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0004_likemodel_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsCountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_viewscount', to='film.filmmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewscount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Views Count',
                'verbose_name_plural': 'Views Counts',
            },
        ),
    ]
